"""Regenerate apps/mochilang-mobile/src/data/mochiSprites.ts from
whatever mochi-N.png files currently live under assets/mochis/.

Metro requires static require() paths — dynamic require() doesn't
resolve in production bundles — so we expand to one literal require
per sprite. Run this after slice-mochis.py changes the sprite count.

Run with:
    python3 apps/mochilang-mobile/scripts/gen-sprites-index.py
"""

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / 'src' / 'data' / 'mochiSprites.ts'
ASSETS = HERE.parent / 'assets' / 'mochis'

# Pick up only the canonical mochi-<n>.png files, sorted numerically.
files = []
for p in ASSETS.iterdir():
    m = re.match(r'^mochi-(\d+)\.png$', p.name)
    if m:
        files.append((int(m.group(1)), p.name))
files.sort()

if not files:
    raise SystemExit(f'no mochi-*.png in {ASSETS}')

# Verify the numbering is contiguous starting at 1 — gaps would mean
# the require() index has nulls, which would break runtime lookups.
expected = list(range(1, len(files) + 1))
actual = [n for n, _ in files]
if actual != expected:
    raise SystemExit(
        f'sprite numbering not contiguous; expected 1..{len(files)} got {actual}'
    )

lines = [
    '// Generated by apps/mochilang-mobile/scripts/gen-sprites-index.py.',
    '// Do not edit by hand — re-run the script after re-slicing.',
    "import type { ImageSourcePropType } from 'react-native'",
    '',
    'export const MOCHI_SPRITES: ImageSourcePropType[] = [',
]
for n, _ in files:
    lines.append(f"  require('../../assets/mochis/mochi-{n}.png'),")
lines.append(']')
lines.append('')
lines.append('export const MOCHI_SPRITE_COUNT = MOCHI_SPRITES.length')
lines.append('')

OUT.write_text('\n'.join(lines))
print(f'wrote {OUT} — {len(files)} sprites')
