// genfallbacks publishes the canonical seed data + derived metadata into
// the web client tree.
//
// "Canonical" data lives at apps/api/internal/seed/data/*.json — the same
// files the backend embeds for DB seeding. This command copies those
// files verbatim into the frontend's data/generated/ directory so the
// web app can bundle them as offline fallbacks.
//
// "Derived" data (currently just league_meta.json) is produced from Go
// constants in the league package, since tier definitions and
// promote/demote thresholds aren't roster content — they're system
// configuration. If those constants ever move, this command stays the one
// place that knows about both halves.
//
// Run via: `make api-gen-fallbacks` or `go run ./cmd/genfallbacks`.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ktdilsiz/mochilang/api/internal/league"
)

const (
	defaultOutDir   = "../web/src/data/generated"
	canonicalSeeds  = "internal/seed/data"
	canonicalNames  = "friends.json,competitors.json"
)

func main() {
	out := flag.String("out", defaultOutDir, "output directory (relative to cwd)")
	flag.Parse()

	abs, err := filepath.Abs(*out)
	if err != nil {
		log.Fatalf("resolve out: %v", err)
	}
	if err := os.MkdirAll(abs, 0o755); err != nil {
		log.Fatalf("mkdir %s: %v", abs, err)
	}

	ts := time.Now().UTC().Format(time.RFC3339)

	// Copy each canonical seed file straight across — the frontend reads
	// them with the same shape we wrote on the API side.
	for _, name := range strings.Split(canonicalNames, ",") {
		if err := copyFile(filepath.Join(canonicalSeeds, name), filepath.Join(abs, name)); err != nil {
			log.Fatalf("copy %s: %v", name, err)
		}
	}

	// league_meta is genuinely derived from Go constants.
	if err := writeLeagueMeta(abs, ts); err != nil {
		log.Fatalf("league_meta.json: %v", err)
	}

	if err := writeIndex(abs, ts); err != nil {
		log.Fatalf("index.ts: %v", err)
	}

	fmt.Printf("✓ wrote fallbacks to %s\n", abs)
}

func copyFile(src, dst string) error {
	body, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, body, 0o644)
}

type leagueMetaOut struct {
	Tiers       []league.Tier `json:"tiers"`
	PromoteRank int           `json:"promoteRank"`
	DemoteRank  int           `json:"demoteRank"`
	CohortSize  int           `json:"cohortSize"`
}

func writeLeagueMeta(dir, ts string) error {
	body, err := json.MarshalIndent(map[string]any{
		"generatedAt": ts,
		"meta": leagueMetaOut{
			Tiers:       league.Tiers,
			PromoteRank: league.PromoteRank,
			DemoteRank:  league.DemoteRank,
			CohortSize:  league.CohortSize,
		},
	}, "", "  ")
	if err != nil {
		return err
	}
	body = append(body, '\n')
	return os.WriteFile(filepath.Join(dir, "league_meta.json"), body, 0o644)
}

// writeIndex emits a small TS module that statically imports the JSON files,
// so frontend code can do `import { friendsFallback } from './generated'`
// without each importer knowing the filenames.
func writeIndex(dir, ts string) error {
	body := strings.Join([]string{
		"// Generated by apps/api/cmd/genfallbacks. Do not edit by hand.",
		"// friends.json and competitors.json are verbatim copies of the",
		"// canonical seeds at apps/api/internal/seed/data/. league_meta.json",
		"// is derived from Go constants in internal/league.",
		"// Last published: " + ts,
		"",
		"import friends from './friends.json'",
		"import competitors from './competitors.json'",
		"import leagueMeta from './league_meta.json'",
		"",
		"export const friendsFallback = friends",
		"export const competitorsFallback = competitors",
		"export const leagueMetaFallback = leagueMeta",
		"",
	}, "\n")
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(body), 0o644)
}
