// genfallbacks publishes the canonical seed data + derived metadata into
// the web client tree.
//
// "Canonical" data lives at apps/api/internal/seed/data/*.json — the same
// files the backend embeds for DB seeding. This command copies those
// files verbatim into the frontend's data/generated/ directory so the
// web app can bundle them as offline fallbacks.
//
// "Derived" data (currently just league_meta.json) is produced from Go
// constants in the league package, since tier definitions and
// promote/demote thresholds aren't roster content — they're system
// configuration. If those constants ever move, this command stays the one
// place that knows about both halves.
//
// Run via: `make api-gen-fallbacks` or `go run ./cmd/genfallbacks`.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ktdilsiz/mochilang/api/internal/content"
	"github.com/ktdilsiz/mochilang/api/internal/league"
)

const (
	defaultOutDir    = "../web/src/data/generated"
	canonicalSeeds   = "internal/seed/data"
	canonicalNames   = "friends.json,competitors.json"
	canonicalContent = "internal/content/data"
)

func main() {
	out := flag.String("out", defaultOutDir, "output directory (relative to cwd)")
	flag.Parse()

	abs, err := filepath.Abs(*out)
	if err != nil {
		log.Fatalf("resolve out: %v", err)
	}
	if err := os.MkdirAll(abs, 0o755); err != nil {
		log.Fatalf("mkdir %s: %v", abs, err)
	}

	ts := time.Now().UTC().Format(time.RFC3339)

	// Copy each canonical seed file straight across — the frontend reads
	// them with the same shape we wrote on the API side.
	for _, name := range strings.Split(canonicalNames, ",") {
		if err := copyFile(filepath.Join(canonicalSeeds, name), filepath.Join(abs, name)); err != nil {
			log.Fatalf("copy %s: %v", name, err)
		}
	}

	// Course content is the assembled wire payload — same bytes the API
	// would return for /api/content/courses/:id. We use the content
	// loader (which embeds and assembles in one step) so the frontend
	// never has to re-implement the per-level merge.
	loader, err := content.NewLoader()
	if err != nil {
		log.Fatalf("load courses: %v", err)
	}
	courseIDs := make([]string, 0, len(loader.List()))
	for _, c := range loader.List() {
		body, ok := loader.Get(c.ID)
		if !ok {
			continue
		}
		dst := filepath.Join(abs, "course-"+c.ID+".json")
		if err := os.WriteFile(dst, body, 0o644); err != nil {
			log.Fatalf("write %s: %v", dst, err)
		}
		courseIDs = append(courseIDs, c.ID)
	}

	// league_meta is genuinely derived from Go constants.
	if err := writeLeagueMeta(abs, ts); err != nil {
		log.Fatalf("league_meta.json: %v", err)
	}

	if err := writeIndex(abs, ts, courseIDs); err != nil {
		log.Fatalf("index.ts: %v", err)
	}

	fmt.Printf("✓ wrote fallbacks to %s\n", abs)
}

func copyFile(src, dst string) error {
	body, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, body, 0o644)
}

type leagueMetaOut struct {
	Tiers       []league.Tier `json:"tiers"`
	PromoteRank int           `json:"promoteRank"`
	DemoteRank  int           `json:"demoteRank"`
	CohortSize  int           `json:"cohortSize"`
}

func writeLeagueMeta(dir, ts string) error {
	body, err := json.MarshalIndent(map[string]any{
		"generatedAt": ts,
		"meta": leagueMetaOut{
			Tiers:       league.Tiers,
			PromoteRank: league.PromoteRank,
			DemoteRank:  league.DemoteRank,
			CohortSize:  league.CohortSize,
		},
	}, "", "  ")
	if err != nil {
		return err
	}
	body = append(body, '\n')
	return os.WriteFile(filepath.Join(dir, "league_meta.json"), body, 0o644)
}

// writeIndex emits a small TS module that statically imports the JSON
// files, so frontend code can do `import { friendsFallback } from
// './generated'` without each importer knowing the filenames. Courses
// are exposed as a `coursesFallback` map keyed by course id.
func writeIndex(dir, ts string, courseIDs []string) error {
	lines := []string{
		"// Generated by apps/api/cmd/genfallbacks. Do not edit by hand.",
		"// friends.json and competitors.json are verbatim copies of the",
		"// canonical seeds at apps/api/internal/seed/data/. course-*.json",
		"// are the wire payload assembled by the content loader from",
		"// apps/api/internal/content/data/<id>/*.json. league_meta.json is",
		"// derived from Go constants in internal/league.",
		"// Last published: " + ts,
		"",
		"import friends from './friends.json'",
		"import competitors from './competitors.json'",
		"import leagueMeta from './league_meta.json'",
	}
	type courseImport struct{ id, varName, file string }
	imports := make([]courseImport, 0, len(courseIDs))
	for _, id := range courseIDs {
		varName := "course_" + strings.ReplaceAll(id, "-", "_")
		imports = append(imports, courseImport{id: id, varName: varName, file: "course-" + id + ".json"})
	}
	for _, ci := range imports {
		lines = append(lines, fmt.Sprintf("import %s from './%s'", ci.varName, ci.file))
	}
	lines = append(lines,
		"",
		"export const friendsFallback = friends",
		"export const competitorsFallback = competitors",
		"export const leagueMetaFallback = leagueMeta",
		"",
		"export const coursesFallback: Record<string, unknown> = {",
	)
	for _, ci := range imports {
		lines = append(lines, fmt.Sprintf("  '%s': %s,", ci.id, ci.varName))
	}
	lines = append(lines, "}", "")
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(strings.Join(lines, "\n")), 0o644)
}
