// genfallbacks publishes the canonical seed data + derived metadata into
// the web client tree.
//
// "Canonical" data lives at apps/api/internal/seed/data/*.json — the same
// files the backend embeds for DB seeding. This command copies those
// files verbatim into the frontend's data/generated/ directory so the
// web app can bundle them as offline fallbacks.
//
// "Derived" data (currently just league_meta.json) is produced from Go
// constants in the league package, since tier definitions and
// promote/demote thresholds aren't roster content — they're system
// configuration. If those constants ever move, this command stays the one
// place that knows about both halves.
//
// Run via: `make api-gen-fallbacks` or `go run ./cmd/genfallbacks`.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ktdilsiz/mochilang/api/internal/league"
)

const (
	defaultOutDir    = "../web/src/data/generated"
	canonicalSeeds   = "internal/seed/data"
	canonicalNames   = "friends.json,competitors.json"
	canonicalContent = "internal/content/data"
)

func main() {
	out := flag.String("out", defaultOutDir, "output directory (relative to cwd)")
	flag.Parse()

	abs, err := filepath.Abs(*out)
	if err != nil {
		log.Fatalf("resolve out: %v", err)
	}
	if err := os.MkdirAll(abs, 0o755); err != nil {
		log.Fatalf("mkdir %s: %v", abs, err)
	}

	ts := time.Now().UTC().Format(time.RFC3339)

	// Copy each canonical seed file straight across — the frontend reads
	// them with the same shape we wrote on the API side.
	for _, name := range strings.Split(canonicalNames, ",") {
		if err := copyFile(filepath.Join(canonicalSeeds, name), filepath.Join(abs, name)); err != nil {
			log.Fatalf("copy %s: %v", name, err)
		}
	}

	// Copy each course content file. Discovers what's there so adding a
	// new course (e.g. `fr-en.json`) doesn't require editing this command.
	courses, err := os.ReadDir(canonicalContent)
	if err != nil {
		log.Fatalf("read %s: %v", canonicalContent, err)
	}
	for _, f := range courses {
		if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
			continue
		}
		// Prefix with `course-` in the bundle to keep the directory
		// readable (so it sorts next to friends.json/competitors.json
		// rather than being alphabetized between them).
		dst := filepath.Join(abs, "course-"+f.Name())
		if err := copyFile(filepath.Join(canonicalContent, f.Name()), dst); err != nil {
			log.Fatalf("copy %s: %v", f.Name(), err)
		}
	}

	// league_meta is genuinely derived from Go constants.
	if err := writeLeagueMeta(abs, ts); err != nil {
		log.Fatalf("league_meta.json: %v", err)
	}

	if err := writeIndex(abs, ts, courses); err != nil {
		log.Fatalf("index.ts: %v", err)
	}

	fmt.Printf("✓ wrote fallbacks to %s\n", abs)
}

func copyFile(src, dst string) error {
	body, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, body, 0o644)
}

type leagueMetaOut struct {
	Tiers       []league.Tier `json:"tiers"`
	PromoteRank int           `json:"promoteRank"`
	DemoteRank  int           `json:"demoteRank"`
	CohortSize  int           `json:"cohortSize"`
}

func writeLeagueMeta(dir, ts string) error {
	body, err := json.MarshalIndent(map[string]any{
		"generatedAt": ts,
		"meta": leagueMetaOut{
			Tiers:       league.Tiers,
			PromoteRank: league.PromoteRank,
			DemoteRank:  league.DemoteRank,
			CohortSize:  league.CohortSize,
		},
	}, "", "  ")
	if err != nil {
		return err
	}
	body = append(body, '\n')
	return os.WriteFile(filepath.Join(dir, "league_meta.json"), body, 0o644)
}

// writeIndex emits a small TS module that statically imports the JSON
// files, so frontend code can do `import { friendsFallback } from
// './generated'` without each importer knowing the filenames. Courses
// are exposed as a `coursesFallback` map keyed by course id.
func writeIndex(dir, ts string, courseFiles []os.DirEntry) error {
	lines := []string{
		"// Generated by apps/api/cmd/genfallbacks. Do not edit by hand.",
		"// friends.json and competitors.json are verbatim copies of the",
		"// canonical seeds at apps/api/internal/seed/data/. course-*.json",
		"// are copies of apps/api/internal/content/data/. league_meta.json",
		"// is derived from Go constants in internal/league.",
		"// Last published: " + ts,
		"",
		"import friends from './friends.json'",
		"import competitors from './competitors.json'",
		"import leagueMeta from './league_meta.json'",
	}
	type courseImport struct{ id, varName, file string }
	var imports []courseImport
	for _, f := range courseFiles {
		if f.IsDir() || !strings.HasSuffix(f.Name(), ".json") {
			continue
		}
		id := strings.TrimSuffix(f.Name(), ".json")
		// Variable name has to be a valid JS identifier — replace dashes.
		varName := "course_" + strings.ReplaceAll(id, "-", "_")
		imports = append(imports, courseImport{id: id, varName: varName, file: "course-" + f.Name()})
	}
	for _, ci := range imports {
		lines = append(lines, fmt.Sprintf("import %s from './%s'", ci.varName, ci.file))
	}
	lines = append(lines,
		"",
		"export const friendsFallback = friends",
		"export const competitorsFallback = competitors",
		"export const leagueMetaFallback = leagueMeta",
		"",
		"export const coursesFallback: Record<string, unknown> = {",
	)
	for _, ci := range imports {
		lines = append(lines, fmt.Sprintf("  '%s': %s,", ci.id, ci.varName))
	}
	lines = append(lines, "}", "")
	return os.WriteFile(filepath.Join(dir, "index.ts"), []byte(strings.Join(lines, "\n")), 0o644)
}
