import { useEffect, useState } from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Switch,
  Text,
  View,
} from 'react-native';
import type * as Speech from 'expo-speech';
import { AppHeader } from '../components/AppHeader';
import { useStore, type SpeechRate } from '../state';
import { listChineseVoices, speak } from '../lib/tts';

type Props = {
  onBack: () => void;
};

const RATE_OPTIONS: { id: SpeechRate; label: string }[] = [
  { id: 'slow', label: 'Slow' },
  { id: 'normal', label: 'Normal' },
  { id: 'fast', label: 'Fast' },
];

const PREVIEW_TEXT = '你好，今天天气很好';

export function AudioScreen({ onBack }: Props) {
  const { prefs, setPrefs } = useStore();
  const [voices, setVoices] = useState<Speech.Voice[] | null>(null);

  useEffect(() => {
    listChineseVoices().then(setVoices);
  }, []);

  return (
    <View style={s.root}>
      <AppHeader title="Audio" leading="back" onLeadingPress={onBack} />
      <ScrollView contentContainerStyle={s.body}>
        <Section title="Speech rate">
          <View style={s.chipRow}>
            {RATE_OPTIONS.map((opt) => {
              const selected = prefs.speechRate === opt.id;
              return (
                <Pressable
                  key={opt.id}
                  onPress={() => setPrefs({ speechRate: opt.id })}
                  style={({ pressed }) => [
                    s.chip,
                    selected && s.chipSelected,
                    pressed && s.chipPressed,
                  ]}
                >
                  <Text
                    style={[s.chipText, selected && s.chipTextSelected]}
                  >
                    {opt.label}
                  </Text>
                </Pressable>
              );
            })}
          </View>
          <Pressable
            onPress={() => speak(PREVIEW_TEXT)}
            style={({ pressed }) => [s.preview, pressed && s.previewPressed]}
          >
            <Text style={s.previewIcon}>🔊</Text>
            <Text style={s.previewText}>Preview · {PREVIEW_TEXT}</Text>
          </Pressable>
        </Section>

        <Section title="Auto-play">
          <View style={s.toggleRow}>
            <View style={s.toggleText}>
              <Text style={s.toggleLabel}>Speak words on tap</Text>
              <Text style={s.toggleHint}>
                When you open a thought bubble, the word plays automatically.
              </Text>
            </View>
            <Switch
              value={prefs.autoPlay}
              onValueChange={(v) => setPrefs({ autoPlay: v })}
            />
          </View>
        </Section>

        <Section title="Voice">
          {voices === null ? (
            <Text style={s.muted}>Looking for installed voices…</Text>
          ) : voices.length === 0 ? (
            <Text style={s.muted}>
              No alternate Chinese voices found on this device. Using the
              system default.
            </Text>
          ) : (
            <View style={s.voiceList}>
              <VoiceRow
                label="System default"
                hint="Picked by your OS"
                selected={!prefs.voiceId}
                onPress={() => setPrefs({ voiceId: undefined })}
              />
              {voices.map((v) => (
                <VoiceRow
                  key={v.identifier}
                  label={v.name ?? v.identifier}
                  hint={v.language}
                  selected={prefs.voiceId === v.identifier}
                  onPress={() => setPrefs({ voiceId: v.identifier })}
                />
              ))}
            </View>
          )}
        </Section>

        <View style={s.footer}>
          <Text style={s.footerText}>
            Speech is generated by your device’s built-in Mandarin voice — no
            audio leaves the device.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <View style={s.section}>
      <Text style={s.sectionTitle}>{title}</Text>
      <View style={s.card}>{children}</View>
    </View>
  );
}

function VoiceRow({
  label,
  hint,
  selected,
  onPress,
}: {
  label: string;
  hint?: string;
  selected: boolean;
  onPress: () => void;
}) {
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [s.voiceRow, pressed && s.voiceRowPressed]}
    >
      <View style={s.voiceText}>
        <Text style={s.voiceLabel}>{label}</Text>
        {hint && <Text style={s.voiceHint}>{hint}</Text>}
      </View>
      <View style={[s.radio, selected && s.radioSelected]}>
        {selected && <View style={s.radioDot} />}
      </View>
    </Pressable>
  );
}

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#fafafa' },
  body: { padding: 16, gap: 20, paddingBottom: 40 },
  section: { gap: 8 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    paddingHorizontal: 4,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e5e7eb',
    gap: 12,
  },
  chipRow: { flexDirection: 'row', gap: 8 },
  chip: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
  },
  chipPressed: { opacity: 0.85 },
  chipSelected: { backgroundColor: '#3b82f6' },
  chipText: { fontSize: 15, fontWeight: '600', color: '#374151' },
  chipTextSelected: { color: '#fff' },
  preview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  previewPressed: { opacity: 0.7 },
  previewIcon: { fontSize: 16 },
  previewText: { fontSize: 14, color: '#3b82f6', fontWeight: '600' },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  toggleText: { flex: 1 },
  toggleLabel: { fontSize: 15, color: '#111827', fontWeight: '600' },
  toggleHint: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  voiceList: { gap: 4 },
  voiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 4,
    gap: 12,
  },
  voiceRowPressed: { opacity: 0.7 },
  voiceText: { flex: 1 },
  voiceLabel: { fontSize: 15, color: '#111827', fontWeight: '500' },
  voiceHint: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioSelected: { borderColor: '#3b82f6' },
  radioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#3b82f6',
  },
  muted: { fontSize: 14, color: '#6b7280', lineHeight: 20 },
  footer: { paddingHorizontal: 4 },
  footerText: { fontSize: 12, color: '#9ca3af', lineHeight: 18 },
});
